# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('smartflow-routing', ['core','internet','point-to-point','userdefinedfunction'])
    module.source = [
        'model/smartflow-routing.cc',
        'helper/smartflow-routing-helper.cc',
        'model/ipv4-smartflow-tag.cc',
        ]

    module_test = bld.create_ns3_module_test_library('smartflow-routing')
    module_test.source = [
        'test/smartflow-routing-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'smartflow-routing'
    headers.source = [
        'model/smartflow-routing.h',
        'helper/smartflow-routing-helper.h',
        'model/ipv4-smartflow-tag.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

